### PR TITLE
lang/i18n: add messages.po nb_NO translations pt.1

### PR DESCRIPTION
**Pull request by AceGentile**
add first part of nb_NO translations to messages.po

### CODE REVIEW

**Comment by madbob** [comment]
Are those strings the same added on the translations platform?
https://hosted.weblate.org/projects/gasdottong/translations/nb_NO/

**Comment by AceGentile** [comment]
sorry, didn't know there was a translations platform. Am I supposed to use weblate to send translations instead of opening prs on github?

**Comment by madbob** [comment]
Yes, Weblate. Contents are eventually merged periodically from there.
Did you used Google Translate? Most of your strings don't match with those already translated on Weblate by Norwegian native speaker...

**Comment by AceGentile** [comment]
I did not use google translate. 
I study/speak norwegian and translated them by mysellf. Asked also a translator speaking natively both italian and norwegian to review them before submitting. Some strings already traslated are slightly different from italian texts. For example:

"utenti" is translated with "Bruker" which means "utente"; I expected "Brukere" (utenti) 
"Calcola Quantità" is translated with "Beregnet mengde" which means "quantità calcolata"; I expected "Beregn mengde" (calcola quantità)
"Data Apertura" in italian is used as "starting date" and it works but when you literally translate it to "Åpningsdato" sound like the day on which a shop is opening; that's why "Startdato" ("starting date") looks more convenient

BTW, I'll close this pr and use weblate.

**Pull request closed without merging**
